{% set name = "odc-io" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35cfa7dd92ddf094bd8781bc66dddc9b3bf445978d5ba89a11a4c373f0cfb781

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - odc.io
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-tools/tree/develop/libs/io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Miscellaneous file IO helper methods
  description: |
    Internal library for the odc.* family of tools

extra:
  recipe-maintainers:
    - kirill888
    - alexgleith
    - omad
    - SpacemanPaul
    - ArianaB
